name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -x  # Enable verbose logging
            cd code-repositories/instagram_clone_final/django_instagram_clone
            git pull origin master
            sudo systemctl restart instagram_clone
          # script: "cd code-repositories/instagram_clone_final/django_instagram_clone && ./.scripts/deploy.sh"
